#!/bin/bash

if [ "$1" == "start" ]; then
sudo systemctl start wg-quick@wg0
fi

if [ "$1" == "stop" ]; then
sudo systemctl stop wg-quick@wg0
fi

if [ "$1" == "restart" ]; then
sudo systemctl restart wg-quick@wg0
fi

if [ "$0" ]; then
sudo systemctl status wg-quick@wg0
fi